/*
 * Decompiled with CFR 0.152.
 */
package io.github.douira.glsl_transformer.ast.print;

public class OutputOptions {
    private boolean printInfo;
    private String headerSuffix;
    public boolean printCustomDirectives = true;

    public OutputOptions() {
        this.printInfo = false;
        this.headerSuffix = null;
    }

    public OutputOptions(boolean printLibraryVersionInfo, String headerSuffix, boolean printCustomDirectives) {
        this.printInfo = printLibraryVersionInfo;
        this.headerSuffix = headerSuffix;
        this.printCustomDirectives = printCustomDirectives;
    }

    public void enablePrintInfo() {
        this.printInfo = true;
    }

    public void disablePrintInfo() {
        this.printInfo = false;
    }

    public void setHeaderSuffix(String headerSuffix) {
        this.headerSuffix = headerSuffix;
    }

    public String getPrintHeader() {
        if (this.printInfo || this.headerSuffix != null) {
            return "// Generated by glsl-transformer" + (String)(this.headerSuffix == null ? "" : " " + this.headerSuffix) + "\n";
        }
        return null;
    }

    public OutputOptions clone() {
        return new OutputOptions(this.printInfo, this.headerSuffix, this.printCustomDirectives);
    }
}

